spring:
  application:
    name: keroshiblog
  datasource:
    url: jdbc:h2:file:./testdb
    username: sa
    password: ""
  messages:
    basename: i18n/messages
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
